server:
  port: 9527
spring:
  application:
    name: cloud-gateway

#    gateway网关路由配置

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #   2、从注册中心动态创建路由
      routes:
        - id: payment_routh     # 路由id，没有固定的规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8001  # 1、固定写死,匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  # 2、利用微服务名进行路由
          predicates:   # 断言，路径匹配进行路由
            - Path=/payment/**  # 也就是之前通过localhost:8001/payment/**的访问 现在要用9527进行访问,隐藏真实地址
#            - After=[时间] # 在这个时间以后才能生效
#            - Cookie=username,admin # 带上这个cookie才能访问,可用curl url --cookie "username=admin" 测试
#            - Header=X-Request-Id,\d+  #请求头
#          filters:  #过滤器
#            - AddRequestHeader=X-Request-Id,id







eureka:
  client:
    # 注册到eureka里，默认为true
    register-with-eureka: true
    # 是否从eurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，配合ribbon负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/  #单机方式访问