
server:
  port: 8080
spring:
  application:
    name: cloud-consumer-order
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#    单机
      defaultZone: http://localhost:7001/eureka/

#    集群
#      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka


# feign默认集成了ribbon
# 可用ribbon设置连接和超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


# 日志，以什么级别监控哪个接口
logging:
  level:
    com.fengx.springcloud.service.PaymentService: debug






