
server:
  port: 8080
spring:
  application:
    name: cloud-consumer-order-hystrix
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#    单机
      defaultZone: http://localhost:7001/eureka/




# feign默认集成了ribbon
# 可用ribbon设置连接和超时时间
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000

#  feign和hystrix的配置
feign:
  hystrix:
    enabled: true







